name: docs_env
channels:
    - tpeulen
    - tpeulen/label/nightly
    - defaults
    - conda-forge
dependencies:
    - tttrlib >=0.0.19
    - phconvert
    - numba
    - scipy
    # the versions are all pinned to reduce the memory load by conda
    # without that, the docs would not build on read the docs
    - pillow
    - sphinx-gallery
    - sphinx=3.1.1
    - nbsphinx=0.7.1
    - jupyter_client=6.1.3 # needed for nbsphinx
    - ipykernel=5.3.0
    - blas=1.0
    - bzip2=1.0.8
    - ca-certificates=2020.1.1
    - certifi=2019.11.28
    - icu=58.2
    - libedit=3.1.20181209
    - libffi=3.2.1
    - libiconv=1.15
    - ncurses=6.2
    - openssl=1.1.1e
    - pip=20.0.2
    - readline=8.0
    - setuptools=46.1.3
    - six=1.14.0
    - sqlite=3.31.1
    - tk=8.6.8
    - wheel=0.34.2
    - xz=5.2.4
    - zlib=1.2.11
    - tifffile
    - pip:
      - babel==2.8.0
      - chardet==3.0.4
      - commonmark==0.9.1
      - cycler==0.10.0
      - docutils==0.16
      - idna==2.9
      - imagesize==1.2.0
      - jinja2==2.11.1
      - kiwisolver==1.1.0
      - latexcodec==2.0.0
      - markupsafe==1.1.1
      # matplotlib=2.2.3 because matplotlib.sphinxext was removed in matplotlib 3.x.x
        #      - matplotlib==2.2.3
      - matplotlib==3.1.3
      - numpy==1.18.1
      - numpydoc==0.9.2
      - oset==0.1.3
      - packaging==20.3
      - pybtex==0.22.2
      - pybtex-docutils==0.2.2
      - pygments==2.6.1
      - pyparsing==2.4.6
      - python-dateutil==2.8.1
      - pytz==2019.3
      - pyyaml==5.3.1
      - recommonmark==0.6.0
      - requests==2.23.0
      - snowballstemmer==2.0.0
      - sphinx-bootstrap-theme==0.7.1
      - sphinx-rtd-theme==0.4.3
      - sphinxcontrib-bibtex==1.0.0
      - sphinxcontrib-websupport==1.2.1
      - urllib3==1.25.8
      - breathe==4.18.0
      - imagecodecs
      - tifffile
