
name: Build and Upload Conda Packages

on:
#  push:
#    branches:
#      - develop
  release:
    types: ['released', 'prereleased']

jobs:
  build:
    name: CondaBuild (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: Display Conda Settings
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: "Set SDK on MacOS (if needed)"
        if: startsWith(matrix.os, 'macos')
        run: tools/install_macos_sdk.sh

      - name: Build Conda Package
        shell: bash -el {0}
        run: |
          mamba install conda-build boa anaconda-client
          cd conda-recipe
          
          # Use older conda_build_config -> boost-cpp 1.78
          curl -sLO  https://raw.githubusercontent.com/conda-forge/conda-forge-pinning-feedstock/084b098a28a7a66e9a0967d156bc55b9ebfc6726/recipe/conda_build_config.yaml
          # curl -sLO https://github.com/conda-forge/conda-forge-pinning-feedstock/raw/main/recipe/conda_build_config.yaml
          conda mambabuild . --output-folder conda-bld

      - name: Upload Conda Package
        shell: bash -el {0}
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u tpeulen --force conda-bld/**/*.tar.bz2

